$axure.loadCurrentPage({
  "url":"page_3.html",
  "generationDate":new Date(1511298644843.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d9fe36a5c92c46e08bc7644e54634143",
    "type":"Axure:Page",
    "name":"Page 3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7c6a0b9663014bbf8c42193209433e47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":66},
            "size":{
              "width":300,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a42da261a9f14e12bd0cdbef3e39682f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":66},
                "size":{
                  "width":300,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b4e5fcdb5dd452f8a77dcb7bf0836a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":34},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d66d878616d4477b9a158f9b2d8d25f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":34},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7c6a0b9663014bbf8c42193209433e47":{
      "scriptId":"u0"},
    "a42da261a9f14e12bd0cdbef3e39682f":{
      "scriptId":"u1"},
    "1b4e5fcdb5dd452f8a77dcb7bf0836a2":{
      "scriptId":"u2"},
    "5d66d878616d4477b9a158f9b2d8d25f":{
      "scriptId":"u3"}}});